// <auto-generated />
namespace School.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gradesChanges2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gradesChanges2));
        
        string IMigrationMetadata.Id
        {
            get { return "202008082224235_gradesChanges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
